[package]
name = "rusty_gears"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
rayon = "1.10.0"
tobj = { version = "4.0.3", features = ["tokio"]}
wgpu = "24.0.3"
winit = { version = "0.30.9", features = ["rwh_06"] }
bytemuck = { version = "1.16", features = [ "derive" ] }
tokio = { version = "1.43.0", features = [ "full" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"]}
egui = "0.31.1"
egui-winit = { version = "0.31.1", default-features = false }
egui-wgpu = "0.31.1"
crossbeam = "0.8.4"
dyn-clone = "1.0.19"
once_cell = "1.21.3"
